apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  # Keep default read-only for unmapped users/groups.
  policy.default: role:readonly
  scopes: '[groups, email]'
  policy.csv: |
    g, {{ .Values.github.rbac.orgGroup | quote }}, role:admin
    g, {{ .Values.github.rbac.adminTeamGroup | quote }}, role:admin
    g, {{ .Values.github.rbac.maintainerTeamGroup | quote }}, role:admin
