apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  # name of the ExternalSecret & Secret which gets created
  name: github-oauth
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: k3s
  target:
    creationPolicy: Owner
  data:
  - secretKey: clientID
    remoteRef:
      # 1password-entry-name
      key: "GitHub OAuth"
      # 1password-field
      property: clientID
  - secretKey: clientSecret
    remoteRef:
      # 1password-entry-name
      key: "GitHub OAuth"
      # 1password-field
      property: clientSecret
  - secretKey: sshPrivateKey
    remoteRef:
      # 1password-entry-name
      key: "GitHub OAuth"
      # 1password-field
      property: sshPrivateKey