apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-deployment
  namespace: {{ .Values.go-api.namespace }}
spec:
  replicas: {{ .Values.go-api.replicaCount }}
  selector:
    matchLabels:
      app: go-api
  strategy: {}
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - image: {{ .Values.go-api.image.repository }}:{{ .Values.go-api.image.tag }}
        name: go-api
        ports:
        - containerPort: {{ .Values.go-api.service.port }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
status: {}
