apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.go_api.service.name }}
  namespace: {{ .Values.go_api.namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.go_api.service.port }}
    protocol: TCP
    targetPort: {{ .Values.go_api.service.targetPort }}
  selector:
    app: {{ .Values.go_api.name }}
status:
  loadBalancer: {}