general:
  namespace: dev
go_api:
  name: go-api
  replicaCount: 1
  image:
    repository: 'mbradleyhome/golang-api-demo'
    tag: 'latest'
    pullPolicy: IfNotPresent
  service:
    name: go-api-svc
    type: ClusterIP
    port: 80
    targetPort: 8080
csharp_api:
  name: csharp-api
  replicaCount: 1
  image:
    repository: 'mbradleyhome/csharp-api-demo'
    tag: 'latest'
    pullPolicy: IfNotPresent
  service:
    name: csharp-api-svc
    type: ClusterIP
    port: 80
    targetPort: 5113
csharp_ui:
  name: csharp-ui
  replicaCount: 1
  image:
    repository: 'mbradleyhome/csharp-ui-demo'
    tag: 'latest'
    pullPolicy: IfNotPresent
  service:
    name: csharp-ui-svc
    type: ClusterIP
    port: 80
    targetPort: 5113
ollama_api:
  name: ollama-api
  replicaCount: 1
  image:
    repository: 'mbradleyhome/ollama-api'
    tag: 'latest'
    pullPolicy: IfNotPresent
  service:
    name: ollama-api-svc
    type: ClusterIP
    port: 80
    targetPort: 8000
