general:
  namespace: dev
go_api:
  name: go-api
  replicaCount: 1
  image:
    repository: 'mbradleyhome/golang-api-demo'
    tag: 'v2'
    pullPolicy: Always
  service:
    name: go-api-svc
    type: ClusterIP
    port: 80
    targetPort: 8080
csharp_api:
  name: csharp-api
  replicaCount: 1
  image:
    repository: 'mbradleyhome/csharp-api-demo'
    tag: 'v3'
    pullPolicy: Always
  service:
    name: csharp-api-svc
    type: ClusterIP
    port: 80
    targetPort: 5113
csharp_ui:
  name: csharp-ui
  replicaCount: 1
  image:
    repository: 'mbradleyhome/csharp-ui-demo'
    tag: 'v1'
    pullPolicy: Always
  service:
    name: csharp-ui-svc
    type: ClusterIP
    port: 80
    targetPort: 5113
python_flask_ui:
  name: python-flask-ui
  replicaCount: 0
  image:
    repository: 'mbradleyhome/python-flask-demo'
    tag: 'v1'
    pullPolicy: Always
  service:
    name: python-flask-ui-svc
    type: ClusterIP
    port: 80
    targetPort: 5000
ollama_api:
  name: ollama-api
  replicaCount: 1
  image:
    repository: 'mbradleyhome/ollama-api'
    tag: 'v1'
    pullPolicy: Always
  service:
    name: ollama-api-svc
    type: ClusterIP
    port: 80
    targetPort: 8000
