---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: csharp-routes
  namespace: {{ .Values.csharp_ui.namespace }}
spec:
  hosts:
  - "{{ .Values.csharp_api.service.name }}.{{ .Values.csharp_ui.namespace }}.svc.cluster.local"
  http:
  - name: "csharp-ui-routes"
    match:
    - method:
        exact: POST
      uri:
        prefix: "/besttimetobyorsellstock"
    route:
    - destination:
        host: "{{ .Values.csharp_api.service.name }}.{{ .Values.csharp_api.namespace }}.svc.cluster.local"
        subset: v1
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: csharp-destinations
  namespace: {{ .Values.csharp_ui.namespace }}
spec:
  host: "{{ .Values.csharp_api.service.name }}.{{ .Values.csharp_api.namespace }}.svc.cluster.local"
  subsets:
  - name: v1
    labels:
      version: v1