---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: csharp-routes
  namespace: {{ .Values.general.namespace }}
spec:
  hosts:
  - "{{ .Values.csharp_api.service.name }}"
  - "{{ .Values.csharp_ui.service.name }}"
  http:
  - name: "csharp-api-routes"
    match:
    - uri:
        prefix: "/besttimetobyorsellstock"
    route:
    - destination:
        host: "{{ .Values.csharp_api.service.name }}.{{ .Values.general.namespace }}.svc.cluster.local"
        subset: v1
    corsPolicy:
      allowOrigins:
      - prefix: "http://csharp-ui.localhost"
      - prefix: "http://csharp-api.localhost"
      - prefix: "http://localhost"
      allowMethods:
      - GET
      - POST
      - OPTIONS
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: csharp-destinations
  namespace: {{ .Values.general.namespace }}
spec:
  host: "{{ .Values.csharp_api.service.name }}.{{ .Values.general.namespace }}.svc.cluster.local"
  subsets:
  - name: v1
    labels:
      version: v1