apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  dex.github.clientID: REPLACE_WITH_GITHUB_OAUTH_CLIENT_ID
  dex.github.clientSecret: REPLACE_WITH_GITHUB_OAUTH_CLIENT_SECRET
