apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.go_api.name }}-deployment"
  namespace: "{{ .Values.go_api.namespace }}"
spec:
  replicas: !!int "{{ .Values.go_api.replicaCount }}"
  selector:
    matchLabels:
      app: "{{ .Values.go_api.name }}"
  strategy: {}
  template:
    metadata:
      labels:
        app: "{{ .Values.go_api.name }}"
    spec:
      containers:
      - image: "{{ .Values.go_api.image.repository }}:{{ .Values.go_api.image.tag }}"
        name: "{{ .Values.go_api.name }}"
        ports:
        - containerPort: !!int "{{ .Values.go_api.service.targetPort }}"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
