apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.csharp_ui.name }}-ingress"
  namespace: "{{ .Values.csharp_ui.namespace }}"
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: "{{ .Values.csharp_ui.name }}.localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.csharp_ui.service.name }}"
                port:
                  number: !!int "{{ .Values.csharp_ui.service.port }}"