apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: csharp-api-pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csharp-api-pod-reader-binding
  namespace: {{ .Values.general.namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.general.namespace }}
roleRef:
  kind: Role
  name: csharp-api-pod-reader
  apiGroup: rbac.authorization.k8s.io