apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.ollama_api.service.name }}"
  namespace: "{{ .Values.general.namespace }}"
  labels:
    istio.io/use-waypoint: "waypoint-{{ .Values.general.namespace }}"
spec:
  ports:
  - name: http
    port: !!int "{{ .Values.ollama_api.service.port }}"
    protocol: TCP
    targetPort: !!int "{{ .Values.ollama_api.service.targetPort }}"
  selector:
    app: "{{ .Values.ollama_api.name }}"
status:
  loadBalancer: {}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: "{{ .Values.ollama_api.service.name }}-allow"
  namespace: "{{ .Values.general.namespace }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.ollama_api.name }}"
  action: ALLOW
  rules:
  - to:
    - operation:
        ports:
        - "{{ .Values.ollama_api.service.port }}"