---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'monitoring-k3d'
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    namespace: 'monitoring'
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: 'kube-prometheus-stack'
      targetRevision: '58.6.0'
      helm:
        valueFiles:
          - values.yaml
      path: 'k3d-cluster/charts/monitoring'
    - repoURL: 'https://github.com/marcobradley/local-kubernetes-cluster-demo.git'
      targetRevision: 'main'
      ref: values
  project: 'default'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
