apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-oauth
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    kind: {{ .Values.github.externalSecrets.store.kind }}
    name: {{ .Values.github.externalSecrets.store.name }}
  target:
    name: {{ .Values.github.externalSecrets.oauth.targetSecretName | default "argocd-github-oauth" }}
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: clientID
      remoteRef:
        key: {{ .Values.github.externalSecrets.oauth.item | quote }}
        property: {{ .Values.github.externalSecrets.oauth.clientIdProperty | quote }}
    - secretKey: clientSecret
      remoteRef:
        key: {{ .Values.github.externalSecrets.oauth.item | quote }}
        property: {{ .Values.github.externalSecrets.oauth.clientSecretProperty | quote }}
